include(ExternalProject)

set(EXT_STAGING_DIR ${CMAKE_CURRENT_BINARY_DIR}/staging${CMAKE_INSTALL_PREFIX})

ExternalProject_Add(dep-spdlog
    GIT_REPOSITORY https://github.com/gabime/spdlog.git
    GIT_TAG v1.8.1
    GIT_SHALLOW ON
    CMAKE_ARGS
        -D CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
        -D CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
        -D CMAKE_STAGING_PREFIX=${EXT_STAGING_DIR}
        -D CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -D CMAKE_VERBOSE_MAKEFILE=ON
)

add_library(spdlog INTERFACE IMPORTED GLOBAL)
set_target_properties(spdlog PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SPDLOG_HEADER_ONLY"
  INTERFACE_INCLUDE_DIRECTORIES "${EXT_STAGING_DIR}/include"
)
add_dependencies(spdlog dep-spdlog)